"""Design tokens: one JSON file, a generated Kotlin object per client.

`contracts/tokens/tokens.json` is the source. Each client has the same names, so
"primary" or "touchTarget" means the same on the web, Android and iOS. This
script writes the Android file; the iOS one joins when iOS starts.

    python contracts/scripts/tokens.py write   # regenerate
    python contracts/scripts/tokens.py check   # fail if the generated file is stale

Standard library only.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "contracts" / "tokens" / "tokens.json"
ANDROID = ROOT / "android" / "core-designsystem" / "src" / "main" / "kotlin" / "app" / "ezpztac" / "designsystem" / "Tokens.kt"

HEX = re.compile(r"^#[0-9A-Fa-f]{6}$")


def load():
    tokens = json.loads(SOURCE.read_text())
    palettes = tokens["colors"]
    names = set(palettes["dark"])
    for theme, palette in palettes.items():
        if set(palette) != names:
            raise SystemExit(f"{theme} palette has different colour names from dark: {sorted(set(palette) ^ names)}")
        for name, value in palette.items():
            if not HEX.match(value):
                raise SystemExit(f"{theme}.{name} is not #RRGGBB: {value!r}")
    return tokens


def upper_first(word):
    return word[0].upper() + word[1:]


def kotlin(tokens):
    out = [
        "// Generated by contracts/scripts/tokens.py from contracts/tokens/tokens.json. Do not edit by hand.",
        "package app.ezpztac.designsystem",
        "",
        "/** The design tokens, as plain numbers so they can be tested on a JVM and read by Compose and by tests alike. */",
        "object Tokens {",
        "    /** Colours as 0xAARRGGBB, one palette per theme. */",
        "    object Colors {",
    ]
    for theme, palette in tokens["colors"].items():
        out.append(f"        object {upper_first(theme)} {{")
        for name, value in palette.items():
            out.append(f"            const val {name}: Long = 0xFF{value[1:].upper()}")
        out.append("        }")
    out += ["    }", "", "    /** In dp. */", "    object Spacing {"]
    out += [f"        const val {k}: Int = {v}" for k, v in tokens["spacing"].items()]
    out += ["    }", "", "    /** In dp. */", "    object Radius {"]
    out += [f"        const val {k}: Int = {v}" for k, v in tokens["radius"].items()]
    out += ["    }", "", "    /** In dp. The touch target is above the 48 dp platform minimum, for gloves and vibration. */", "    object Size {"]
    out += [f"        const val {k}: Int = {v}" for k, v in tokens["size"].items()]
    out += ["    }", "", "    /** Size and line height in sp; `mono` is a monospaced face, for grids and key numbers. */", "    object Type {"]
    out.append("        data class Style(val size: Int, val lineHeight: Int, val weight: Int, val mono: Boolean)")
    out.append("")
    for name, style in tokens["type"].items():
        mono = "true" if style["mono"] else "false"
        out.append(f"        val {name} = Style({style['size']}, {style['lineHeight']}, {style['weight']}, {mono})")
    out += ["    }", "}", ""]
    return "\n".join(out)


def main(argv):
    mode = argv[1] if len(argv) > 1 else "check"
    generated = kotlin(load())
    if mode == "write":
        ANDROID.parent.mkdir(parents=True, exist_ok=True)
        ANDROID.write_text(generated)
        print(f"wrote {ANDROID.relative_to(ROOT)}")
        return 0
    if mode == "check":
        if not ANDROID.exists() or ANDROID.read_text() != generated:
            print(f"{ANDROID.relative_to(ROOT)} is out of date: run python contracts/scripts/tokens.py write")
            return 1
        print("tokens are current")
        return 0
    print("usage: tokens.py write|check")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
