// Generated by contracts/scripts/tokens.py from contracts/tokens/tokens.json. Do not edit by hand.
package app.ezpztac.designsystem

/** The design tokens, as plain numbers so they can be tested on a JVM and read by Compose and by tests alike. */
object Tokens {
    /** Colours as 0xAARRGGBB, one palette per theme. */
    object Colors {
        object Dark {
            const val background: Long = 0xFF092137
            const val surface: Long = 0xFF0F2C47
            const val surfaceVariant: Long = 0xFF16385A
            const val onBackground: Long = 0xFFE7EAEE
            const val onSurface: Long = 0xFFE7EAEE
            const val onSurfaceVariant: Long = 0xFF9CA3AF
            const val primary: Long = 0xFF5AA7D4
            const val onPrimary: Long = 0xFF092137
            const val secondary: Long = 0xFF00B5E2
            const val onSecondary: Long = 0xFF092137
            const val outline: Long = 0xFF3D84B3
            const val error: Long = 0xFFEF4444
            const val onError: Long = 0xFF05080C
            const val warning: Long = 0xFFF59E0B
            const val success: Long = 0xFF22C55E
            const val scrim: Long = 0xFF000000
        }
        object Light {
            const val background: Long = 0xFFF4F8FB
            const val surface: Long = 0xFFFFFFFF
            const val surfaceVariant: Long = 0xFFEAF2F8
            const val onBackground: Long = 0xFF1F2937
            const val onSurface: Long = 0xFF1F2937
            const val onSurfaceVariant: Long = 0xFF6B7280
            const val primary: Long = 0xFF2F6F9F
            const val onPrimary: Long = 0xFFFFFFFF
            const val secondary: Long = 0xFF0077A0
            const val onSecondary: Long = 0xFFFFFFFF
            const val outline: Long = 0xFFCFD8E2
            const val error: Long = 0xFFDC2626
            const val onError: Long = 0xFFFFFFFF
            const val warning: Long = 0xFFB45309
            const val success: Long = 0xFF15803D
            const val scrim: Long = 0xFF000000
        }
        object Night {
            const val background: Long = 0xFF07090C
            const val surface: Long = 0xFF0D1117
            const val surfaceVariant: Long = 0xFF131920
            const val onBackground: Long = 0xFFCF6B63
            const val onSurface: Long = 0xFFCF6B63
            const val onSurfaceVariant: Long = 0xFFB8685F
            const val primary: Long = 0xFFD66B64
            const val onPrimary: Long = 0xFF0D1117
            const val secondary: Long = 0xFFCA6159
            const val onSecondary: Long = 0xFF0D1117
            const val outline: Long = 0xFF6B3A36
            const val error: Long = 0xFFFF5A4F
            const val onError: Long = 0xFF0D1117
            const val warning: Long = 0xFFC48A2C
            const val success: Long = 0xFF4C7A4A
            const val scrim: Long = 0xFF000000
        }
    }

    /** In dp. */
    object Spacing {
        const val xs: Int = 4
        const val sm: Int = 8
        const val md: Int = 12
        const val lg: Int = 16
        const val xl: Int = 24
        const val xxl: Int = 32
    }

    /** In dp. */
    object Radius {
        const val sm: Int = 6
        const val md: Int = 10
        const val lg: Int = 16
        const val sheet: Int = 24
    }

    /** In dp. The touch target is above the 48 dp platform minimum, for gloves and vibration. */
    object Size {
        const val touchTarget: Int = 56
        const val iconSmall: Int = 20
        const val icon: Int = 24
        const val sheetPeek: Int = 120
        const val railCollapsed: Int = 72
    }

    /** Size in sp; `mono` is a monospaced face, for grids and key numbers. */
    object Type {
        data class Style(val size: Int, val weight: Int, val mono: Boolean)

        val keyNumber = Style(32, 700, true)
        val headline = Style(24, 600, false)
        val title = Style(20, 600, false)
        val body = Style(16, 400, false)
        val label = Style(14, 500, false)
        val caption = Style(12, 400, false)
        val grid = Style(18, 600, true)
    }
}
