"""The Material Symbols the screens draw, as Android vector drawables in this module's res/drawable.

Material Symbols Rounded (Apache License 2.0, https://fonts.google.com/icons), weight 400, grade 0, optical size 24, the
style docs/native-design draws with. `symbols.txt` lists them, one per line: a name, or `name fill` for the filled form.
The drawables are checked in; run this only to add or change one (it needs the network).

    python android/core-designsystem/symbols.py

Standard library only.
"""

import re
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
LIST = HERE / "symbols.txt"
OUT = HERE / "src" / "main" / "res" / "drawable"
KOTLIN = HERE / "src" / "main" / "kotlin" / "app" / "ezpztac" / "designsystem" / "EzpzIcons.kt"
URL = "https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsrounded/{name}/{style}/24px.svg"
NAME = re.compile(r"^[a-z0-9_]+$")
PATH = re.compile(r'<path d="([^"]+)"\s*/>')
# Path data is numbers and the SVG path commands, nothing else.
PATH_DATA = re.compile(r"^[MmLlHhVvCcSsQqTtAaZz0-9.,\- ]+$")


def drawable(path_data):
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Material Symbols Rounded (Apache License 2.0). Written by android/core-designsystem/symbols.py: do not edit by hand. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp"\n'
        '    android:height="24dp"\n'
        '    android:viewportWidth="960"\n'
        '    android:viewportHeight="960">\n'
        '    <group android:translateY="960">\n'
        f'        <path android:fillColor="#FFFFFFFF" android:pathData="{path_data}" />\n'
        "    </group>\n"
        "</vector>\n"
    )


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    wanted = []
    for line in LIST.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        name, filled = parts[0], len(parts) > 1 and parts[1] == "fill"
        if not NAME.match(name):
            raise SystemExit(f"not a symbol name: {line!r}")
        wanted.append((name, filled))
    for name, filled in wanted:
        url = URL.format(name=name, style="fill1" if filled else "default")
        with urllib.request.urlopen(url, timeout=30) as response:
            svg = response.read().decode("utf-8")
        paths = PATH.findall(svg)
        if len(paths) != 1 or not PATH_DATA.match(paths[0]):
            raise SystemExit(f"{name}: expected one plain path, got {len(paths)}")
        target = OUT / f"ic_{name}{'_fill' if filled else ''}.xml"
        target.write_text(drawable(paths[0]), encoding="utf-8", newline="\n")
    KOTLIN.write_text(kotlin(wanted), encoding="utf-8", newline="\n")
    print(f"wrote {len(wanted)} drawables to {OUT.relative_to(HERE.parent.parent)}, and {KOTLIN.name}")
    return 0


def camel(name, filled):
    first, *rest = name.split("_")
    word = first + "".join(part[:1].upper() + part[1:] for part in rest)
    if word[0].isdigit():
        word = "n" + word
    return word + ("Fill" if filled else "")


def kotlin(wanted):
    out = [
        "// Generated by android/core-designsystem/symbols.py from symbols.txt. Do not edit by hand.",
        "package app.ezpztac.designsystem",
        "",
        "import androidx.annotation.DrawableRes",
        "",
        "/**",
        " * The Material Symbols Rounded the screens draw (Apache License 2.0), as drawable resources: `painterResource(EzpzIcons.route)`.",
        " * `...Fill` is the filled form. To add one, list it in symbols.txt and run symbols.py.",
        " */",
        "object EzpzIcons {",
    ]
    for name, filled in wanted:
        resource = f"ic_{name}{'_fill' if filled else ''}"
        out.append(f"    @DrawableRes val {camel(name, filled)}: Int = R.drawable.{resource}")
    out += ["}", ""]
    return "\n".join(out)


if __name__ == "__main__":
    sys.exit(main())
